version: '2.1'
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend