"""made all user related cols not null

Revision ID: f0d26c6d3c6e
Revises: 72c4a65ed085
Create Date: 2023-04-18 22:23:05.746993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0d26c6d3c6e'
down_revision = '72c4a65ed085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'department_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('role', 'feature',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'feature',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('role', 'department_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
