"""init

Revision ID: 1972ba346608
Revises: 
Create Date: 2023-04-06 18:06:41.219970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1972ba346608'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('department', sa.Integer(), nullable=True),
                    sa.Column('feature', sa.String(length=255), nullable=True),
                    sa.Column('create', sa.Boolean(), nullable=False),
                    sa.Column('read', sa.Boolean(), nullable=False),
                    sa.Column('update', sa.Boolean(), nullable=False),
                    sa.Column('delete', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['department'], ['department.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('pic', sa.String(length=255), nullable=True),
                    sa.Column('department', sa.Integer(), nullable=False),
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['department'], ['department.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('session',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('login_time', sa.DateTime(), nullable=False),
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('styles',
                    sa.Column('product_id', sa.String(), nullable=False),
                    sa.Column('style_id', sa.String(), nullable=False),
                    sa.Column('gender', sa.String(), nullable=False),
                    sa.Column('vertical', sa.String(), nullable=False),
                    sa.Column('fabric_category', sa.String(), nullable=False),
                    sa.Column('brand', sa.String(), nullable=False),
                    sa.Column('usage', sa.String(), nullable=False),
                    sa.Column('brick', sa.String(), nullable=False),
                    sa.Column('product', sa.String(), nullable=False),
                    sa.Column('sub_product', sa.String(), nullable=False),
                    sa.Column('look', sa.String(), nullable=False),
                    sa.Column('target_audience', sa.String(), nullable=False),
                    sa.Column('fit', sa.String(), nullable=False),
                    sa.Column('mrp', sa.Integer(), nullable=True),
                    sa.Column('cost', sa.Integer(), nullable=True),
                    sa.Column('tags', sa.String(), nullable=True),
                    sa.Column('colour_family', sa.String(), nullable=False),
                    sa.Column('primary_colour', sa.String(), nullable=False),
                    sa.Column('secondary_colour', sa.String(), nullable=True),
                    sa.Column('tertiary_colour', sa.String(), nullable=True),
                    sa.Column('season', sa.String(), nullable=True),
                    sa.Column('exclusive', sa.String(), nullable=False),
                    sa.Column('garment_pattern', sa.String(), nullable=True),
                    sa.Column('print_pattern_type', sa.String(), nullable=True),
                    sa.Column('number_of_components', sa.String(), nullable=True),
                    sa.Column('number_of_pockets', sa.Integer(), nullable=True),
                    sa.Column('pocket_type', sa.String(), nullable=True),
                    sa.Column('neck', sa.String(), nullable=True),
                    sa.Column('collar', sa.String(), nullable=True),
                    sa.Column('placket', sa.String(), nullable=True),
                    sa.Column('length', sa.String(), nullable=True),
                    sa.Column('sleeve_length', sa.String(), nullable=True),
                    sa.Column('sleeve_type', sa.String(), nullable=True),
                    sa.Column('hemline', sa.String(), nullable=True),
                    sa.Column('waist_rise', sa.String(), nullable=True),
                    sa.Column('closure', sa.String(), nullable=True),
                    sa.Column('footwear_ankle_type', sa.String(), nullable=True),
                    sa.Column('footwear_insole', sa.String(), nullable=True),
                    sa.Column('fabric_code', sa.String(), nullable=True),
                    sa.Column('fabric_rate', sa.Integer(), nullable=True),
                    sa.Column('fabric_story', sa.String(), nullable=True),
                    sa.Column('fabric_composition', sa.String(), nullable=True),
                    sa.Column('fabric_hsn', sa.Integer(), nullable=True),
                    sa.Column('fabric_weave_pattern', sa.String(), nullable=True),
                    sa.Column('fabric_vendor', sa.String(), nullable=True),
                    sa.Column('denim_cast', sa.String(), nullable=True),
                    sa.Column('denim_wash', sa.String(), nullable=True),
                    sa.Column('wash_care', sa.String(), nullable=True),
                    sa.Column('footwear_upper_material', sa.String(), nullable=True),
                    sa.Column('footwear_sole_material', sa.String(), nullable=True),
                    sa.Column('first_grn_date', sa.Date(), nullable=True),
                    sa.Column('first_live_date', sa.Date(), nullable=True),
                    sa.Column('first_sold_date', sa.Date(), nullable=True),
                    sa.Column('images', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('product_id')
                    )
    op.create_index(op.f('ix_styles_product_id'), 'styles', ['product_id'], unique=False)
    op.create_table('sales',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('sale_date', sa.Date(), nullable=False),
                    sa.Column('product_id', sa.String(), nullable=False),
                    sa.Column('ean', sa.BigInteger(), nullable=False),
                    sa.Column('qty', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('mrp_per_pc', sa.Float(), nullable=False),
                    sa.Column('sp_per_pc', sa.Float(), nullable=False),
                    sa.Column('margin_per_pc', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['styles.product_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sizes',
                    sa.Column('product_id', sa.String(), nullable=False),
                    sa.Column('standard_size', sa.String(), nullable=False),
                    sa.Column('barcode_size', sa.String(), nullable=False),
                    sa.Column('ean', sa.BigInteger(), nullable=True),
                    sa.Column('myntra_id', sa.BigInteger(), nullable=True),
                    sa.Column('ajio_id', sa.BigInteger(), nullable=True),
                    sa.Column('ajio_ean', sa.BigInteger(), nullable=True),
                    sa.Column('garment_waist', sa.Float(), nullable=True),
                    sa.Column('inseam_length', sa.Float(), nullable=True),
                    sa.Column('to_fit_waist', sa.Float(), nullable=True),
                    sa.Column('across_shoulder', sa.Float(), nullable=True),
                    sa.Column('chest', sa.Float(), nullable=True),
                    sa.Column('front_length', sa.Float(), nullable=True),
                    sa.Column('to_fit_foot_length', sa.Float(), nullable=True),
                    sa.Column('shoe_weight', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['styles.product_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('product_id', 'standard_size'),
                    sa.UniqueConstraint('ean')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sizes')
    op.drop_table('sales')
    op.drop_index(op.f('ix_styles_product_id'), table_name='styles')
    op.drop_table('styles')
    op.drop_table('session')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_table('department')
    # ### end Alembic commands ###
