"""made department not null

Revision ID: 72c4a65ed085
Revises: b83ee0f564ba
Create Date: 2023-04-18 22:21:19.284639

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72c4a65ed085'
down_revision = 'b83ee0f564ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'department_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'department_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
