"""changed fkey id

Revision ID: b83ee0f564ba
Revises: f5a385fc4ed4
Create Date: 2023-04-18 22:15:44.119736

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b83ee0f564ba'
down_revision = 'f5a385fc4ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'email')
    op.drop_column('department', 'department')
    op.drop_column('department', 'deleted')
    op.drop_column('department', 'pic')
    op.add_column('role', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint('role_department_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_column('role', 'department')
    op.add_column('user', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_department_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_department_fkey', 'user', 'department', ['department'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'department_id')
    op.add_column('role', sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_department_fkey', 'role', 'department', ['department'], ['id'], ondelete='CASCADE')
    op.drop_column('role', 'department_id')
    op.add_column('department', sa.Column('pic', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('department', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('department', sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('department', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
