"""added sales tables

Revision ID: 18084361ebac
Revises: 75b622315e55
Create Date: 2023-10-09 12:27:36.978367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18084361ebac'
down_revision = '75b622315e55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grn',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('ean', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year', 'month', 'ean')
    )
    op.create_table('wip',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('ean', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year', 'month', 'ean')
    )
    op.create_table('returns',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('ean', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'year', 'month', 'ean')
    )
    op.create_table('soh',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('ean', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'year', 'month', 'ean')
    )
    op.add_column('sales', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('qty', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('sp_per_pc', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'sales', 'channel', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sales', 'master_cost')
    op.drop_column('sales', 'product_id')
    op.drop_column('sales', 'channel')
    op.drop_column('sales', 'net_qty')
    op.drop_column('sales', 'sold_qty')
    op.drop_column('sales', 'avg_mrp_per_pc')
    op.drop_column('sales', 'avg_discount_per_pc')
    op.drop_column('sales', 'avg_margin_per_pc')
    op.drop_column('sales', 'return_qty')
    op.drop_column('sales', 'master_mrp')
    op.drop_column('sales', 'avg_profit_per_pc')
    op.drop_column('sales', 'avg_sp_per_pc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('avg_sp_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('avg_profit_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('master_mrp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('return_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('avg_margin_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('avg_discount_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('avg_mrp_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('sold_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('net_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('master_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'sp_per_pc')
    op.drop_column('sales', 'qty')
    op.drop_column('sales', 'channel_id')
    op.drop_table('soh')
    op.drop_table('returns')
    op.drop_table('wip')
    op.drop_table('grn')
    op.drop_table('channel')
    # ### end Alembic commands ###
