"""changed sales db structure

Revision ID: 764a8c3bb569
Revises: dfcd4632358e
Create Date: 2023-06-08 20:54:12.619840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '764a8c3bb569'
down_revision = 'dfcd4632358e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('channel', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('sales', sa.Column('sold_qty', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('return_qty', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('net_qty', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('avg_mrp_per_pc', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('avg_discount_per_pc', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('avg_sp_per_pc', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('avg_margin_per_pc', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('avg_profit_per_pc', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('master_mrp', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('master_cost', sa.Float(), nullable=True))
    op.alter_column('sales', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('sales_product_id_fkey', 'sales', type_='foreignkey')
    op.drop_column('sales', 'sale_date')
    op.drop_column('sales', 'mrp_per_pc')
    op.drop_column('sales', 'qty')
    op.drop_column('sales', 'id')
    op.drop_column('sales', 'margin_per_pc')
    op.drop_column('sales', 'status')
    op.drop_column('sales', 'sp_per_pc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sp_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('margin_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('sales', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('mrp_per_pc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key('sales_product_id_fkey', 'sales', 'styles', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.alter_column('sales', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sales', 'master_cost')
    op.drop_column('sales', 'master_mrp')
    op.drop_column('sales', 'avg_profit_per_pc')
    op.drop_column('sales', 'avg_margin_per_pc')
    op.drop_column('sales', 'avg_sp_per_pc')
    op.drop_column('sales', 'avg_discount_per_pc')
    op.drop_column('sales', 'avg_mrp_per_pc')
    op.drop_column('sales', 'net_qty')
    op.drop_column('sales', 'return_qty')
    op.drop_column('sales', 'sold_qty')
    op.drop_column('sales', 'date')
    op.drop_column('sales', 'channel')
    # ### end Alembic commands ###
